<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHV6CplN\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHV6CplN/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHV6CplN.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHV6CplN\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerHV6CplN\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'HV6CplN',
    'container.build_id' => '82f206cb',
    'container.build_time' => 1567773347,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHV6CplN');
