<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVYxLVzu\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVYxLVzu/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVYxLVzu.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVYxLVzu\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerVYxLVzu\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'VYxLVzu',
    'container.build_id' => '86b32fac',
    'container.build_time' => 1566750552,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVYxLVzu');
